//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PILLARSALT_KIOSK
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionInfo
    {
        public long Id { get; set; }
        public string IPAddress { get; set; }
        public string AlternateIP { get; set; }
        public Nullable<long> SocketPort { get; set; }
        public string KeyName { get; set; }
        public byte[] PrivateKey { get; set; }
        public byte[] PublicKey { get; set; }
        public string ProfilingIP { get; set; }
        public Nullable<long> Entry { get; set; }
        public Nullable<long> Active { get; set; }
        public string KeyPass { get; set; }
    }
}
