//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acc_Payments()
        {
            this.Acc_Retirements = new HashSet<Acc_Retirements>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public Nullable<decimal> WHT { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string PayMode { get; set; }
        public Nullable<int> BankAcc { get; set; }
        public Nullable<decimal> AmountReleased { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> BkBalanceAtPayment { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public string TransactionNo { get; set; }
        public string BankGLAcc { get; set; }
        public string RetirementStatus { get; set; }
        public string PayeeBank { get; set; }
        public string PayeeBankAccNo { get; set; }
        public Nullable<int> PostSeq { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        public virtual Acc_BankMapping Acc_BankMapping { get; set; }
        public virtual InventoryVoucher InventoryVoucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_Retirements> Acc_Retirements { get; set; }
    }
}
