//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Pending_Transactions
    {
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public string Trancode { get; set; }
        public string CurrencyCode { get; set; }
        public string TranCurrency { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<System.DateTime> Valuedate { get; set; }
        public string Userid { get; set; }
        public string Narration { get; set; }
        public Nullable<int> Postseq { get; set; }
        public Nullable<decimal> TranAmount { get; set; }
        public Nullable<decimal> BaseAmount { get; set; }
        public Nullable<int> crossrate { get; set; }
        public Nullable<decimal> charge { get; set; }
        public Nullable<int> Reversal { get; set; }
        public Nullable<int> AccountModule { get; set; }
        public Nullable<decimal> chkNUm { get; set; }
        public string tellerno { get; set; }
        public Nullable<int> branchcode { get; set; }
        public string authid { get; set; }
        public Nullable<int> status { get; set; }
        public string batchno { get; set; }
        public string overideid { get; set; }
        public Nullable<int> serviceid { get; set; }
        public string settlementacct { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> GLBatchNo { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> entry { get; set; }
        public string AuthoriseId { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        public virtual InventoryVoucher InventoryVoucher { get; set; }
    }
}
