//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_CurrencyCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acc_CurrencyCode()
        {
            this.Acc_Accounts_BankDetails = new HashSet<Acc_Accounts_BankDetails>();
            this.Acc_BankMapping = new HashSet<Acc_BankMapping>();
            this.Acc_Budget = new HashSet<Acc_Budget>();
            this.Acc_Retirements = new HashSet<Acc_Retirements>();
            this.Admin_ApprovalLimits = new HashSet<Admin_ApprovalLimits>();
            this.Admin_WorkOrder = new HashSet<Admin_WorkOrder>();
            this.CustomerPayments = new HashSet<CustomerPayment>();
            this.Expenses = new HashSet<Expens>();
            this.InventoryOrderDetails = new HashSet<InventoryOrderDetail>();
            this.Real_Property_ClientLeasing = new HashSet<Real_Property_ClientLeasing>();
            this.Real_RentalLog = new HashSet<Real_RentalLog>();
            this.Real_RentalUnit = new HashSet<Real_RentalUnit>();
        }
    
        public int Id { get; set; }
        public string CrncyCode { get; set; }
        public string Description { get; set; }
        public string Country { get; set; }
        public string status { get; set; }
        public string countrycode { get; set; }
        public Nullable<bool> DefaultCurrency { get; set; }
        public string DrAccount { get; set; }
        public string CrAccount { get; set; }
        public Nullable<decimal> LastRate { get; set; }
        public Nullable<decimal> FcyBalance { get; set; }
        public Nullable<decimal> LcyBalance { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> CurrentRate { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public string Symbol { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_Accounts_BankDetails> Acc_Accounts_BankDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_BankMapping> Acc_BankMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_Budget> Acc_Budget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_Retirements> Acc_Retirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_ApprovalLimits> Admin_ApprovalLimits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_WorkOrder> Admin_WorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPayment> CustomerPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expens> Expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryOrderDetail> InventoryOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_Property_ClientLeasing> Real_Property_ClientLeasing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_RentalLog> Real_RentalLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_RentalUnit> Real_RentalUnit { get; set; }
    }
}
