//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_ResourceBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin_ResourceBooking()
        {
            this.Admin_ResourceBooking1 = new HashSet<Admin_ResourceBooking>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string RecurrenceRule { get; set; }
        public Nullable<int> RecurrenceParentId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> CollectionTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string MacAddress { get; set; }
        public Nullable<int> ResourceOperatorID { get; set; }
        public string DeviationExcuse { get; set; }
        public string CancellationReason { get; set; }
        public Nullable<int> ResourceRequestId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        public virtual Admin_Resource_Request Admin_Resource_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_ResourceBooking> Admin_ResourceBooking1 { get; set; }
        public virtual Admin_ResourceBooking Admin_ResourceBooking2 { get; set; }
        public virtual Admin_Resources Admin_Resources { get; set; }
        public virtual StaffBio StaffBio { get; set; }
    }
}
