//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin_WorkOrder()
        {
            this.Admin_WorkOrder_Progression = new HashSet<Admin_WorkOrder_Progression>();
            this.Admin_WorkOrder_PaySchedule = new HashSet<Admin_WorkOrder_PaySchedule>();
            this.Admin_WorkOrder_Documents = new HashSet<Admin_WorkOrder_Documents>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> SerialAcc { get; set; }
        public Nullable<int> ExpenseTypeId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> ParentOrderId { get; set; }
        public Nullable<int> RequisitionId { get; set; }
        public Nullable<int> MaintenanceId { get; set; }
        public Nullable<System.DateTime> DateDone { get; set; }
        public string Status { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> Verifier { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> AverageJobQuality { get; set; }
        public Nullable<decimal> AverageAttitude { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Mobilization { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_WorkOrder_Progression> Admin_WorkOrder_Progression { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_WorkOrder_PaySchedule> Admin_WorkOrder_PaySchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_WorkOrder_Documents> Admin_WorkOrder_Documents { get; set; }
        public virtual Asset_Maintenance_Decision Asset_Maintenance_Decision { get; set; }
        public virtual Expens Expens { get; set; }
        public virtual ExpenseType ExpenseType { get; set; }
        public virtual Acc_CurrencyCode Acc_CurrencyCode { get; set; }
        public virtual Account Account { get; set; }
    }
}
