//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_FixedAssets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset_FixedAssets()
        {
            this.Asset_Depreciation = new HashSet<Asset_Depreciation>();
            this.Asset_Documents = new HashSet<Asset_Documents>();
            this.Asset_FixedAsset_Faults = new HashSet<Asset_FixedAsset_Faults>();
            this.Asset_Maintenance_Schedule = new HashSet<Asset_Maintenance_Schedule>();
            this.Asset_Relocations = new HashSet<Asset_Relocations>();
            this.TMS_Deposit = new HashSet<TMS_Deposit>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string SerialNo { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<System.DateTime> ProcurementDate { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string FixedAssetNo { get; set; }
        public Nullable<decimal> CurrentValue { get; set; }
        public string Status { get; set; }
        public Nullable<int> WarrantyStatus { get; set; }
        public Nullable<System.DateTime> WarrantyStart { get; set; }
        public Nullable<System.DateTime> WarrantyEnd { get; set; }
        public byte[] ItemPhoto { get; set; }
        public Nullable<int> CurrentLocationId { get; set; }
        public Nullable<decimal> UsefulYears { get; set; }
        public Nullable<decimal> SalvageValue { get; set; }
        public Nullable<int> ServiceInterval { get; set; }
        public Nullable<decimal> UsageServiceLimit { get; set; }
        public string UsageUnits { get; set; }
        public Nullable<int> FreeServiceDays { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> AssetMobility { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<bool> leasable { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        public virtual Asset_AssetLocations Asset_AssetLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Depreciation> Asset_Depreciation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Documents> Asset_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_FixedAsset_Faults> Asset_FixedAsset_Faults { get; set; }
        public virtual Asset_Mobility Asset_Mobility { get; set; }
        public virtual Asset_Models Asset_Models { get; set; }
        public virtual Asset_WarrantyStatus Asset_WarrantyStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Maintenance_Schedule> Asset_Maintenance_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Relocations> Asset_Relocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_Deposit> TMS_Deposit { get; set; }
        public virtual InventoryItem InventoryItem { get; set; }
        public virtual InventoryVendor InventoryVendor { get; set; }
        public virtual UnitMeasure UnitMeasure { get; set; }
    }
}
