//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_FixedAsset_Faults
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> FaultId { get; set; }
        public string Severity { get; set; }
        public string ActionStatus { get; set; }
        public Nullable<int> VisitId { get; set; }
        public byte[] Photo { get; set; }
        public byte[] ClosePhoto { get; set; }
        public Nullable<decimal> CurrentUsage { get; set; }
        public string Cause { get; set; }
        public string QuickFix { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        public virtual Asset_CommonFaults Asset_CommonFaults { get; set; }
        public virtual Asset_FixedAssets Asset_FixedAssets { get; set; }
        public virtual Asset_Inspection_Visit Asset_Inspection_Visit { get; set; }
    }
}
