//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPayment
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> SerialACC { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string Paymode { get; set; }
        public string TellerCheque { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<int> PostSeq { get; set; }
        public string UserID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public Nullable<int> BankID { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string AuthoriseId { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        public virtual Acc_BankMapping Acc_BankMapping { get; set; }
        public virtual Acc_CurrencyCode Acc_CurrencyCode { get; set; }
        public virtual Account Account { get; set; }
    }
}
