//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDMS_Document_Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDMS_Document_Template()
        {
            this.Admin_Requisition_Documents = new HashSet<Admin_Requisition_Documents>();
            this.Admin_Template_Documents = new HashSet<Admin_Template_Documents>();
            this.Admin_WorkOrder_Documents = new HashSet<Admin_WorkOrder_Documents>();
            this.Admin_WorkOrder_Progression_Documents = new HashSet<Admin_WorkOrder_Progression_Documents>();
            this.Asset_Documents = new HashSet<Asset_Documents>();
            this.EDMS_Documents = new HashSet<EDMS_Documents>();
            this.EDMS_Template_Categories = new HashSet<EDMS_Template_Categories>();
            this.HR_KPI = new HashSet<HR_KPI>();
            this.HR_Leave_Request_Documents = new HashSet<HR_Leave_Request_Documents>();
            this.Inventory_Voucher_Documents = new HashSet<Inventory_Voucher_Documents>();
            this.Prj_ProjectDocuments = new HashSet<Prj_ProjectDocuments>();
            this.Prj_TaskDocuments = new HashSet<Prj_TaskDocuments>();
            this.Outsourcing_Contract_Document = new HashSet<Outsourcing_Contract_Document>();
            this.Outsourcing_TenderDocuments = new HashSet<Outsourcing_TenderDocuments>();
            this.LEGAL_Litigation_Documents = new HashSet<LEGAL_Litigation_Documents>();
            this.Real_Property_Manifest = new HashSet<Real_Property_Manifest>();
            this.Real_Unit_Manifest = new HashSet<Real_Unit_Manifest>();
            this.Acc_Retirement_Documents = new HashSet<Acc_Retirement_Documents>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> MaxFileSize { get; set; }
        public string AllowedExtensions { get; set; }
        public string Notes { get; set; }
        public string CommonType { get; set; }
        public Nullable<int> SampleDocument { get; set; }
        public string Category { get; set; }
        public string TemplateCode { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_Requisition_Documents> Admin_Requisition_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_Template_Documents> Admin_Template_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_WorkOrder_Documents> Admin_WorkOrder_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_WorkOrder_Progression_Documents> Admin_WorkOrder_Progression_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Documents> Asset_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDMS_Documents> EDMS_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDMS_Template_Categories> EDMS_Template_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_KPI> HR_KPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Leave_Request_Documents> HR_Leave_Request_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Voucher_Documents> Inventory_Voucher_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prj_ProjectDocuments> Prj_ProjectDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prj_TaskDocuments> Prj_TaskDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outsourcing_Contract_Document> Outsourcing_Contract_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outsourcing_TenderDocuments> Outsourcing_TenderDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEGAL_Litigation_Documents> LEGAL_Litigation_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_Property_Manifest> Real_Property_Manifest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_Unit_Manifest> Real_Unit_Manifest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_Retirement_Documents> Acc_Retirement_Documents { get; set; }
    }
}
