//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Appraisal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_Appraisal()
        {
            this.HR_Appraisal_Ratio = new HashSet<HR_Appraisal_Ratio>();
            this.HR_CareerNeeds = new HashSet<HR_CareerNeeds>();
            this.HR_Goals = new HashSet<HR_Goals>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string AppraisalCode { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public Nullable<System.DateTime> GoalSettingStart { get; set; }
        public Nullable<System.DateTime> GoalSettingEnd { get; set; }
        public Nullable<System.DateTime> AssessmentStart { get; set; }
        public Nullable<System.DateTime> AssessmentEnd { get; set; }
        public string Status { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public Nullable<System.DateTime> LMAssessmentStart { get; set; }
        public Nullable<System.DateTime> LMAssessmentEnd { get; set; }
        public Nullable<System.DateTime> SecondLMStart { get; set; }
        public Nullable<System.DateTime> SecondLMEnd { get; set; }
        public Nullable<System.DateTime> HRReviewStart { get; set; }
        public Nullable<System.DateTime> HRReviewEnd { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Appraisal_Ratio> HR_Appraisal_Ratio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_CareerNeeds> HR_CareerNeeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Goals> HR_Goals { get; set; }
    }
}
