//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryVendor()
        {
            this.Asset_FixedAssets = new HashSet<Asset_FixedAssets>();
            this.Asset_Maintenance_Schedule = new HashSet<Asset_Maintenance_Schedule>();
            this.Outsourcing_TenderBids = new HashSet<Outsourcing_TenderBids>();
            this.Real_PropertyValuation = new HashSet<Real_PropertyValuation>();
        }
    
        public int VendorID { get; set; }
        public string CompanyName { get; set; }
        public string RegistrationNo { get; set; }
        public string CompanyEmail { get; set; }
        public string Address { get; set; }
        public Nullable<int> CreditRating { get; set; }
        public string GSM { get; set; }
        public Nullable<bool> Active { get; set; }
        public string PurchasingWebServiceURL { get; set; }
        public Nullable<int> VendorCategoryID { get; set; }
        public string ContactPerson { get; set; }
        public string TaxAccount { get; set; }
        public string AccPayable { get; set; }
        public string DiscountAccount { get; set; }
        public Nullable<int> BankID { get; set; }
        public string AccountNo { get; set; }
        public string UserID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<int> SerialAcc { get; set; }
        public Nullable<int> GLBatchNo { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string AuthoriseId { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_FixedAssets> Asset_FixedAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Maintenance_Schedule> Asset_Maintenance_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outsourcing_TenderBids> Outsourcing_TenderBids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_PropertyValuation> Real_PropertyValuation { get; set; }
        public virtual Product Product { get; set; }
        public virtual ACCBank ACCBank { get; set; }
        public virtual Account Account { get; set; }
    }
}
