//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryVoucher()
        {
            this.Inventory_Voucher_Documents = new HashSet<Inventory_Voucher_Documents>();
            this.Acc_Payments = new HashSet<Acc_Payments>();
            this.Acc_Pending_Transactions = new HashSet<Acc_Pending_Transactions>();
        }
    
        public int VoucherID { get; set; }
        public Nullable<int> LPO { get; set; }
        public string VoucherType { get; set; }
        public Nullable<int> SerialAcc { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string UserID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaidStatus { get; set; }
        public Nullable<decimal> AmountReleased { get; set; }
        public string ChequeNo { get; set; }
        public string Narration { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> VoucherSourceID { get; set; }
        public Nullable<int> PostSeq { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> entry { get; set; }
        public string AuthoriseId { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public string AssociatedExpenseAcct { get; set; }
        public Nullable<int> ExpenseType { get; set; }
        public Nullable<int> ParentVoucherID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Voucher_Documents> Inventory_Voucher_Documents { get; set; }
        public virtual InventoryPurchaseOrder InventoryPurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_Payments> Acc_Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_Pending_Transactions> Acc_Pending_Transactions { get; set; }
        public virtual Account Account { get; set; }
    }
}
