//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outsourcing_Tender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Outsourcing_Tender()
        {
            this.Outsourcing_Contract = new HashSet<Outsourcing_Contract>();
            this.Outsourcing_TenderBids = new HashSet<Outsourcing_TenderBids>();
            this.Outsourcing_TenderDocuments = new HashSet<Outsourcing_TenderDocuments>();
            this.Outsourcing_TenderEvaluation = new HashSet<Outsourcing_TenderEvaluation>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string TenderReferenceNo { get; set; }
        public string TenderType { get; set; }
        public Nullable<int> AssociatedProjectId { get; set; }
        public Nullable<bool> RequiresNDA { get; set; }
        public string SubmissionFormat { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string ContactStaff { get; set; }
        public Nullable<bool> RequireEOI { get; set; }
        public Nullable<bool> RequiresPreQualification { get; set; }
        public string SOWDocumentID { get; set; }
        public Nullable<decimal> BidFee { get; set; }
        public Nullable<int> SOW { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outsourcing_Contract> Outsourcing_Contract { get; set; }
        public virtual Outsourcing_StatementOfWork Outsourcing_StatementOfWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outsourcing_TenderBids> Outsourcing_TenderBids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outsourcing_TenderDocuments> Outsourcing_TenderDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outsourcing_TenderEvaluation> Outsourcing_TenderEvaluation { get; set; }
    }
}
