//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CRMLeads = new HashSet<CRMLead>();
            this.InventoryPricings = new HashSet<InventoryPricing>();
            this.InventoryVendors = new HashSet<InventoryVendor>();
            this.LEGAl_Counsel = new HashSet<LEGAl_Counsel>();
            this.LEGAL_Litigants = new HashSet<LEGAL_Litigants>();
            this.ProductServices = new HashSet<ProductService>();
            this.StaffEmpStatus = new HashSet<StaffEmpStatu>();
            this.Accounts = new HashSet<Account>();
            this.ACCProformas = new HashSet<ACCProforma>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<short> CategoryID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<decimal> OpeningCharge { get; set; }
        public Nullable<decimal> MonthlyContribution { get; set; }
        public string LiabilityAccounts { get; set; }
        public string AccountReceivable { get; set; }
        public string AccountPayable { get; set; }
        public string IncomeAccount { get; set; }
        public string Expenses { get; set; }
        public string TaxAccount { get; set; }
        public string CashAccount { get; set; }
        public string UnearnedIncomeAccount { get; set; }
        public string RegistrationAccount { get; set; }
        public string CapitationAccount { get; set; }
        public string InventoryAccount { get; set; }
        public string ProductionAccount { get; set; }
        public Nullable<int> MaxNumber { get; set; }
        public Nullable<int> Expires { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> DebitLimit { get; set; }
        public Nullable<int> GLBatchNo { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string AuthoriseId { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<int> ShipmentAcc { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMLead> CRMLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryPricing> InventoryPricings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryVendor> InventoryVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEGAl_Counsel> LEGAl_Counsel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEGAL_Litigants> LEGAL_Litigants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductService> ProductServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffEmpStatu> StaffEmpStatus { get; set; }
        public virtual AccountEntity AccountEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCProforma> ACCProformas { get; set; }
    }
}
