//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Real_Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Real_Property()
        {
            this.Asset_AssetLocations = new HashSet<Asset_AssetLocations>();
            this.Real_Property_Manifest = new HashSet<Real_Property_Manifest>();
            this.Real_PropertyAnalysis = new HashSet<Real_PropertyAnalysis>();
            this.Real_PropertyFeatures = new HashSet<Real_PropertyFeatures>();
            this.Real_PropertyValuation = new HashSet<Real_PropertyValuation>();
            this.Real_RentalUnit = new HashSet<Real_RentalUnit>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> PropertyType { get; set; }
        public string PropertyCode { get; set; }
        public string Title { get; set; }
        public Nullable<int> AcquisitionType { get; set; }
        public string Notes { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public Nullable<int> MaxFloors { get; set; }
        public Nullable<System.DateTime> AcquisitionDate { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public Nullable<int> EstateId { get; set; }
        public string OldCode { get; set; }
        public string Condition { get; set; }
        public Nullable<decimal> AllowedBuildingRatio { get; set; }
        public Nullable<int> MinFloors { get; set; }
        public Nullable<decimal> BuildingSqm { get; set; }
        public Nullable<int> BuildingFloors { get; set; }
        public string Permit { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<decimal> AcquisitionCost { get; set; }
        public Nullable<decimal> Term { get; set; }
        public string Town { get; set; }
        public string Region { get; set; }
        public Nullable<bool> ForSale { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string PropertyClass { get; set; }
        public Nullable<bool> TenantIsClient { get; set; }
        public byte[] MainPhoto { get; set; }
        public byte[] SidePhoto { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public string MoreDetails { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_AssetLocations> Asset_AssetLocations { get; set; }
        public virtual CRM_Partners CRM_Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_Property_Manifest> Real_Property_Manifest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_PropertyAnalysis> Real_PropertyAnalysis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_PropertyFeatures> Real_PropertyFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_PropertyValuation> Real_PropertyValuation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_RentalUnit> Real_RentalUnit { get; set; }
    }
}
