//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Real_UBAProperties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Real_UBAProperties()
        {
            this.Real_Property_ClientLeasing = new HashSet<Real_Property_ClientLeasing>();
        }
    
        public int Id { get; set; }
        public string OldPropertyId { get; set; }
        public Nullable<int> PropertyType { get; set; }
        public string Address { get; set; }
        public Nullable<int> StateId { get; set; }
        public string OfficeType { get; set; }
        public string Description { get; set; }
        public string Town { get; set; }
        public string Region { get; set; }
        public string Bank { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> NetBookValue { get; set; }
        public Nullable<decimal> RentalValuation { get; set; }
        public Nullable<decimal> CapitalValuation { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> DateLeased { get; set; }
        public Nullable<decimal> TermInYears { get; set; }
        public Nullable<System.DateTime> LeaseCommenced { get; set; }
        public Nullable<System.DateTime> LeaseExpires { get; set; }
        public string RentedArea { get; set; }
        public string TitleType { get; set; }
        public Nullable<decimal> AnnualRent { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        public virtual CRM_Clients CRM_Clients { get; set; }
        public virtual CRM_Partners CRM_Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_Property_ClientLeasing> Real_Property_ClientLeasing { get; set; }
        public virtual state state { get; set; }
    }
}
