//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Real_RentalUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Real_RentalUnit()
        {
            this.Real_RentalLog = new HashSet<Real_RentalLog>();
            this.Real_ServiceCharge = new HashSet<Real_ServiceCharge>();
            this.Real_Unit_Manifest = new HashSet<Real_Unit_Manifest>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public string RentalCode { get; set; }
        public Nullable<int> RentalType { get; set; }
        public Nullable<decimal> RentalCost { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> NoInProperty { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        public virtual Real_Frequency Real_Frequency { get; set; }
        public virtual Real_Property Real_Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_RentalLog> Real_RentalLog { get; set; }
        public virtual Real_UnitType Real_UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_ServiceCharge> Real_ServiceCharge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Real_Unit_Manifest> Real_Unit_Manifest { get; set; }
        public virtual Acc_CurrencyCode Acc_CurrencyCode { get; set; }
    }
}
