//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffBio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffBio()
        {
            this.Admin_Appointments = new HashSet<Admin_Appointments>();
            this.Admin_ResourceBooking = new HashSet<Admin_ResourceBooking>();
            this.HR_Goals = new HashSet<HR_Goals>();
            this.HR_Queries = new HashSet<HR_Queries>();
            this.HR_Schooling = new HashSet<HR_Schooling>();
            this.HR_Suspensions = new HashSet<HR_Suspensions>();
            this.HR_TAT_Monitor = new HashSet<HR_TAT_Monitor>();
            this.HR_ThriftDetails = new HashSet<HR_ThriftDetails>();
            this.IT_AllowedDevices = new HashSet<IT_AllowedDevices>();
            this.Prj_ProjectDetails = new HashSet<Prj_ProjectDetails>();
            this.StaffAttendances = new HashSet<StaffAttendance>();
            this.StaffBonus = new HashSet<StaffBonu>();
            this.StaffTimes = new HashSet<StaffTime>();
            this.StaffZKUsers = new HashSet<StaffZKUser>();
            this.TMS_MachineBagDetachment = new HashSet<TMS_MachineBagDetachment>();
            this.Departments = new HashSet<Department>();
            this.Sys_Event_UserNotify_Filter = new HashSet<Sys_Event_UserNotify_Filter>();
        }
    
        public int StaffId { get; set; }
        public string Description { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> LevelID { get; set; }
        public string LineManager { get; set; }
        public string EmployQualification { get; set; }
        public string DisengagementReason { get; set; }
        public Nullable<System.DateTime> DisengagementDate { get; set; }
        public string DisengagementType { get; set; }
        public Nullable<bool> Disengaged { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> GLBatchNo { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string AuthoriseId { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<int> EmployTypeId { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_Appointments> Admin_Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin_ResourceBooking> Admin_ResourceBooking { get; set; }
        public virtual CRMContact CRMContact { get; set; }
        public virtual HR_Applicants HR_Applicants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Goals> HR_Goals { get; set; }
        public virtual HR_Posts HR_Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Queries> HR_Queries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Schooling> HR_Schooling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Suspensions> HR_Suspensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_TAT_Monitor> HR_TAT_Monitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_ThriftDetails> HR_ThriftDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_AllowedDevices> IT_AllowedDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prj_ProjectDetails> Prj_ProjectDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAttendance> StaffAttendances { get; set; }
        public virtual StaffEmpStatu StaffEmpStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffBonu> StaffBonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffTime> StaffTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffZKUser> StaffZKUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMS_MachineBagDetachment> TMS_MachineBagDetachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Department Department { get; set; }
        public virtual Level Level { get; set; }
        public virtual SchoolBranch SchoolBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Event_UserNotify_Filter> Sys_Event_UserNotify_Filter { get; set; }
    }
}
