//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Event_Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Event_Subscription()
        {
            this.HR_TAT = new HashSet<HR_TAT>();
            this.Sys_Event_Notification = new HashSet<Sys_Event_Notification>();
            this.Sys_Event_NotifyMode = new HashSet<Sys_Event_NotifyMode>();
            this.Sys_Event_SubscriptionAction = new HashSet<Sys_Event_SubscriptionAction>();
            this.Sys_Event_UserNotify_Filter = new HashSet<Sys_Event_UserNotify_Filter>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> TheModuleId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> PrivilegeId { get; set; }
        public Nullable<int> PostId { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<bool> PriorityIM { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    
        public virtual HR_Posts HR_Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_TAT> HR_TAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Event_Notification> Sys_Event_Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Event_NotifyMode> Sys_Event_NotifyMode { get; set; }
        public virtual Sys_Events Sys_Events { get; set; }
        public virtual sys_tablist sys_tablist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Event_SubscriptionAction> Sys_Event_SubscriptionAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Event_UserNotify_Filter> Sys_Event_UserNotify_Filter { get; set; }
    }
}
