//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bankgl
    {
        public string GLNumber { get; set; }
        public string AcctName { get; set; }
        public string BranchCode { get; set; }
        public string Gl_ClassCode { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DT_Lst_Month { get; set; }
        public Nullable<decimal> Last_Month_Balance { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Last_Night_Balance { get; set; }
        public Nullable<decimal> BKBalance { get; set; }
        public Nullable<decimal> TpostDebit { get; set; }
        public Nullable<decimal> TpostCredit { get; set; }
        public string Blocked { get; set; }
        public string Closed { get; set; }
        public Nullable<int> reconLen { get; set; }
        public Nullable<int> post { get; set; }
        public Nullable<decimal> BBF { get; set; }
        public string ProdType { get; set; }
        public Nullable<int> Pointing { get; set; }
        public string typeP { get; set; }
        public string userid { get; set; }
        public string authid { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> populate { get; set; }
        public string oldGLno { get; set; }
        public Nullable<decimal> last_night_balance2 { get; set; }
        public Nullable<int> Swing { get; set; }
        public Nullable<decimal> last_month_balance2 { get; set; }
        public Nullable<decimal> last_month_balance1 { get; set; }
        public Nullable<System.DateTime> last_eom2 { get; set; }
        public Nullable<System.DateTime> last_eom1 { get; set; }
        public Nullable<decimal> currmondiff { get; set; }
        public Nullable<decimal> lastmondiff { get; set; }
        public Nullable<decimal> lastno { get; set; }
        public Nullable<decimal> VIADA001 { get; set; }
        public Nullable<decimal> Premi002 { get; set; }
        public Nullable<int> GLBatchNo { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> entry { get; set; }
        public string AuthoriseId { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    }
}
