//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CASAAccount
    {
        public string branchcode { get; set; }
        public string productcode { get; set; }
        public string accountnumber { get; set; }
        public string accounttitle { get; set; }
        public Nullable<decimal> customerid { get; set; }
        public string officercode { get; set; }
        public string taxcode1 { get; set; }
        public string taxcode2 { get; set; }
        public Nullable<decimal> Cintrate { get; set; }
        public Nullable<decimal> Dintrate { get; set; }
        public Nullable<int> CrIntVar { get; set; }
        public Nullable<int> DrIntVar { get; set; }
        public string Sourcecode { get; set; }
        public Nullable<int> CHKIntWaiver { get; set; }
        public string AssetValue { get; set; }
        public Nullable<int> Loan_Term { get; set; }
        public string Loan_Purpose { get; set; }
        public Nullable<decimal> Loan_Amount { get; set; }
        public Nullable<decimal> Intrest { get; set; }
        public string CurrencyCode { get; set; }
        public string Contribution { get; set; }
        public string PaymentMode { get; set; }
        public string SectorCode { get; set; }
        public Nullable<decimal> CSAsumD { get; set; }
        public Nullable<decimal> CSAsumC { get; set; }
        public Nullable<decimal> Netposting { get; set; }
        public string AccountModule { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<decimal> LNbalance { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> BKBalance { get; set; }
        public Nullable<decimal> ODLimit { get; set; }
        public Nullable<decimal> SuspBal { get; set; }
        public string userid { get; set; }
        public Nullable<decimal> tod_limit { get; set; }
        public Nullable<decimal> unclearedbal { get; set; }
        public Nullable<decimal> HoldBal { get; set; }
        public Nullable<decimal> SIBal { get; set; }
        public Nullable<int> Overline { get; set; }
        public string authid { get; set; }
        public Nullable<decimal> totdebit { get; set; }
        public Nullable<decimal> totcredit { get; set; }
        public Nullable<decimal> totcharge { get; set; }
        public string accountdesc { get; set; }
        public string subbranch { get; set; }
        public string sweep { get; set; }
        public string acctstaffid { get; set; }
        public Nullable<int> DisableView { get; set; }
        public string oldAcctno { get; set; }
        public Nullable<decimal> last_month_balance { get; set; }
        public Nullable<int> lien { get; set; }
        public Nullable<decimal> intaccrued { get; set; }
        public Nullable<System.DateTime> lastdatepay { get; set; }
        public Nullable<decimal> cotval { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> penalrate { get; set; }
        public Nullable<decimal> intaccrueddaily { get; set; }
        public Nullable<decimal> accrueddate { get; set; }
        public Nullable<int> daysaccrued { get; set; }
        public Nullable<System.DateTime> lastdateaccrued { get; set; }
        public Nullable<int> Classified { get; set; }
        public Nullable<decimal> Drbal { get; set; }
        public Nullable<decimal> Crbal { get; set; }
        public Nullable<int> countrec { get; set; }
        public Nullable<System.DateTime> lastoddate { get; set; }
        public Nullable<decimal> expense { get; set; }
        public Nullable<decimal> ODincome { get; set; }
        public Nullable<int> GLBatchNo { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> entry { get; set; }
        public string AuthoriseId { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    }
}
