//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UBA_PropertyTem
    {
        public int id { get; set; }
        public string colum1 { get; set; }
        public string colum2 { get; set; }
        public string colum3 { get; set; }
        public string colum4 { get; set; }
        public string colum5 { get; set; }
        public string colum6 { get; set; }
        public string colum7 { get; set; }
        public string colum8 { get; set; }
        public string colum9 { get; set; }
        public string colum10 { get; set; }
        public string colum11 { get; set; }
        public string colum12 { get; set; }
        public string colum13 { get; set; }
        public string colum14 { get; set; }
        public string colum15 { get; set; }
        public string colum16 { get; set; }
        public string colum17 { get; set; }
        public string colum18 { get; set; }
        public string colum19 { get; set; }
        public string colum20 { get; set; }
        public string colum21 { get; set; }
        public string colum22 { get; set; }
        public string colum23 { get; set; }
        public string colum24 { get; set; }
        public string colum25 { get; set; }
        public string colum26 { get; set; }
        public string colum27 { get; set; }
        public string colum28 { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CurrentStage { get; set; }
        public string UserId { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    }
}
