//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class zkem_USERINFO
    {
        public int USERID { get; set; }
        public string Badgenumber { get; set; }
        public string SSN { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string TITLE { get; set; }
        public string PAGER { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<System.DateTime> HIREDDAY { get; set; }
        public string street { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string OPHONE { get; set; }
        public string FPHONE { get; set; }
        public Nullable<short> VERIFICATIONMETHOD { get; set; }
        public Nullable<short> DEFAULTDEPTID { get; set; }
        public Nullable<short> SECURITYFLAGS { get; set; }
        public Nullable<short> ATT { get; set; }
        public Nullable<short> INLATE { get; set; }
        public Nullable<short> OUTEARLY { get; set; }
        public Nullable<short> OVERTIME { get; set; }
        public Nullable<short> SEP { get; set; }
        public Nullable<short> HOLIDAY { get; set; }
        public string MINZU { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<short> LUNCHDURATION { get; set; }
        public byte[] PHOTO { get; set; }
        public string mverifypass { get; set; }
        public byte[] Notes { get; set; }
        public Nullable<int> privilege { get; set; }
        public Nullable<short> InheritDeptSch { get; set; }
        public Nullable<short> InheritDeptSchClass { get; set; }
        public Nullable<short> AutoSchPlan { get; set; }
        public Nullable<int> MinAutoSchInterval { get; set; }
        public Nullable<short> RegisterOT { get; set; }
        public Nullable<short> InheritDeptRule { get; set; }
        public Nullable<short> EMPRIVILEGE { get; set; }
        public string CardNo { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public Nullable<int> GLBatchNo { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    }
}
