//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PillarSalt.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class zkem_CHECKEXACT
    {
        public int EXACTID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<short> ISADD { get; set; }
        public string YUYIN { get; set; }
        public Nullable<short> ISMODIFY { get; set; }
        public Nullable<short> ISDELETE { get; set; }
        public Nullable<short> INCOUNT { get; set; }
        public Nullable<short> ISCOUNT { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string ReviewerId { get; set; }
        public string OverrideId { get; set; }
        public Nullable<int> GLBatchNo { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string AuthoriseId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RelatorKey { get; set; }
        public Nullable<System.DateTime> ApprovalEntry { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<int> StartModuleID { get; set; }
        public string CurrentStage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Token { get; set; }
        public string EditReason { get; set; }
        public string TokenOwner { get; set; }
        public string TokenManifestId { get; set; }
        public string DeclineId { get; set; }
        public Nullable<System.DateTime> ReviewEntry { get; set; }
        public string DeclineReason { get; set; }
        public string ApprovalComment { get; set; }
        public string ReviewerComment { get; set; }
        public string UpdateLocker { get; set; }
        public string TMSResponse { get; set; }
    }
}
