'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConnectionInfo
    Public Property Id As Long
    Public Property IPAddress As String
    Public Property AlternateIP As String
    Public Property SocketPort As Nullable(Of Long)
    Public Property KeyName As String
    Public Property PrivateKey As Byte()
    Public Property PublicKey As Byte()
    Public Property ProfilingIP As String
    Public Property Entry As Nullable(Of Long)
    Public Property Active As Nullable(Of Long)
    Public Property KeyPass As String

End Class
